// All reusable variables here
#let myLang = "it"
#let myName = "Alessandro Carraro"
#let myMatricola = "2000548"
#let myTitle = "Sviluppo di un Sistema di Generazione Basato su Recupero delle Informazioni (RAG) per l'Analisi e l'Automazione dei Processi Aziendali"
#let myDegree = "Tesi di laurea"
#let myUni = "Università degli Studi di Padova"
#let myDepartment = "Dipartimento di Matematica ''Tullio Levi-Civita''"
#let myFaculty = "Corso di Laurea in Informatica"
#let profTitle = "Prof. "
#let myProf = "Lamberto Ballan"
#let myCompany = "SpazioDev"
#let myTutor = "Matteo Forzan"
#let myLocation = "Padova"
#let myAA = "2023-2024"
#let myTime = "Dicembre 2024"