name: Build Typst document

on:
  push:
    branches:
      - develop

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Typst document
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ

      - name: Commit and push PDF to develop
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add main.pdf
          git commit -m "Add compiled PDF [skip ci]"
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}